/**
 * This is the default Docusaurus configuration.
 * Many values defined here are source from site-config/site-config.ts
 *
 * To avoid merge conflicts, do not edit this file. To override configuration,
 * use siteConfig.docusaurusConfig
 */

import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import { themes as prismThemes } from "prism-react-renderer";
import siteConfig from "./site-config/site-config";
import merge from "lodash.merge";

const config: Config = {
  title: `${siteConfig.company.name} Workflow Builder`,
  tagline: `Connect ${siteConfig.company.name} to the other apps you use`,
  favicon: "img/favicon.ico",
  url: siteConfig.site.url,
  baseUrl: siteConfig.site.baseUrl,
  onBrokenLinks: "throw", // Throw errors during the build process when links are broken
  onBrokenMarkdownLinks: "throw",
  onBrokenAnchors: "throw",
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  presets: [
    [
      "classic",
      {
        docs: { routeBasePath: "/", sidebarPath: "./sidebars.ts" },
        blog: false,
        theme: { customCss: "./site-config/custom.css" },
      } satisfies Preset.Options,
    ],
  ],
  themeConfig: {
    navbar: siteConfig.navbar,
    footer: siteConfig.footer,
    colorMode: siteConfig.colorMode,
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
  future: {
    experimental_faster: true,
  },
};

// Merge this config with optional user-provided config
export default merge(config, siteConfig.docusaurusConfig);
