import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import siteConfig from "./site-config";

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    "get-started",
    {
      type: "category",
      label: siteConfig.phrases["%EMBEDDED_WORKFLOW_BUILDER%"],
      collapsed: false,
      items: [
        "building",
        "branching",
        "looping",
        "triggering",
        "testing",
        "publishing",
        "oauth2",
        "error-handling",
        "http-requests",
        "custom-code",
      ],
    },
    {
      type: "category",
      label: "Connectors",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "connectors" }],
      link: {
        type: "generated-index",
        title: "Connectors",
      },
    },
  ],
};

export default sidebars;
