import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    "home",
    {
      type: "category",
      label: "Connectors",
      items: [{ type: "autogenerated", dirName: "connectors" }],
    },
  ],
};

export default sidebars;
